-- Constructing a nested conjunction p ∧ q ∧ p

theorem test (p q : Prop) (hp : p) (hq : q) : p ∧ q ∧ p := by
  apply And.intro
  exact hp
  apply And.intro
  exact hq
  exact hp

-- Same proof as above, but using And.intro directly as a function

theorem test_short (p q : Prop) (hp : p) (hq : q) : p ∧ q ∧ p := by
 apply And.intro hp
 exact And.intro hq hp

-- Distributivity of conjunction over disjunction:
-- p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r)
example (p q r : Prop) : p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r) := by
apply Iff.intro
. intro h
  apply Or.elim (And.right h)
  . intro hq
    apply Or.inl
    apply And.intro
    . exact h.1
    . exact hq
  . intro hr
    apply Or.inr
    apply And.intro
    . exact h.1
    . exact hr
. intro h
  apply Or.elim h
  . intro hpq
    apply And.intro
    . exact hpq.1
    . apply  Or.inl
      exact  hpq.2
  . intro hpr
    apply And.intro
    . exact hpr.1
    . apply Or.inr
      exact hpr.2

-- Equality transitivity:
-- from a = b and a = c, prove c = b
example : ∀ a b c : Nat , a = b → a = c → c = b := by
  intros
  apply Eq.trans
  apply Eq.symm
  assumption
  assumption

-- Same proof using unhygienic mode to access autogenerated names
example : ∀ a b c : Nat , a = b → a = c → c = b := by unhygienic
  intros
  apply Eq.trans
  apply Eq.symm
  exact a_2
  exact a_1

-- Fully explicit lambda-term proof of equality transitivity
example : ∀ a b c : Nat , a = b → a = c → c = b :=
  (fun a b c => fun h1 : a = b => fun h2 : a = c => Eq.trans (Eq.symm h2) h1)

-- Rearranging conjunction inside an existential witness:
-- ∃ x, p x ∧ q x → ∃ x, q x ∧ p x
example (p q : α → Prop) : (∃ x, p x ∧ q x) → ∃ x, q x ∧ p x := by
  intro ⟨w, hpw, hqw⟩
  exact ⟨w, hqw, hpw⟩

-- Swapping the sides of a disjunction inside an existential witness
example (p q : α → Prop) : (∃ x, p x ∨ q x) → ∃ x, q x ∨ p x := by
  intro
  | ⟨w, Or.inl h⟩ => exact ⟨w, Or.inr h⟩
  | ⟨w, Or.inr h⟩ => exact ⟨w, Or.inl h⟩

-- Demonstrates use of case labels after apply And.intro
theorem test1 (p q : Prop) (hp : p) (hq : q) : p ∧ q ∧ p := by
  apply And.intro
  case left => exact hp
  case right =>
    apply And.intro
    case left => exact hq
    case right => exact hp

-- Renaming automatically generated hypotheses using rename_i
example : ∀ a b c d : Nat, a = b → a = d → a = c → c = b := by
  intros
  rename_i h1 _ h2
  apply Eq.trans
  apply Eq.symm
  exact h2
  exact h1

-- revert moves a local variable back into the goal
example (x : Nat) : x = x := by
  revert x
  intro y
  rfl

-- Reverting x turns it into a universally quantified variable again
example (x y : Nat) (h : x = y) : y = x := by
  revert x
  intros
  apply Eq.symm
  assumption

-- generalize replaces a concrete term with a fresh variable
-- and adds an equality hypothesis
example : 3 = 3 := by
  generalize 3 = x
  revert x
  intro y
  rfl

-- Simple pattern matching on Nat using cases
open Nat
example (P : Nat → Prop)
    (h₀ : P 0) (h₁ : ∀ n, P (succ n))
    (m : Nat) : P m := by
  cases m with
  | zero    => exact h₀
  | succ m' => exact h₁ m'

-- Classical logic:
-- from p → (q ∨ r), derive (p → q) ∨ (p → r)
-- requires excluded middle

open Classical

variable (p q r : Prop)

example : (p → q ∨ r) → ((p → q) ∨ (p → r)) := by
  intro hp
  by_cases hq : p → q
  · exact Or.inl hq
  · right
    intro hp'
    have hqr : q ∨ r := hp hp'
    cases hqr with
    | inl hq' =>
        exfalso
        apply hq
        intro _
        exact hq'
    | inr hr =>
        exact hr

variable (p q r : Prop)

example (p q : Prop) : ¬(p → q) → p ∧ ¬q := by
  intro h
  by_cases hpq : p ∧ ¬q
  · exact hpq
  · have pq : p → q := by
      intro hp
      by_cases hq :q
      · exact hq
      · exact False.elim (hpq (And.intro hp hq))
    exact False.elim (h pq)


example : (p → q) → (¬p ∨ q) := by
  intro h
  by_cases hp:p
  · exact Or.inr (h hp)
  · exact Or.inl hp

-- Law of excluded middle
example : p ∨ ¬p := by
  by_cases hp:p
  · exact Or.inl hp
  · exact Or.inr hp

-- De Morgan's law for disjunction
example : ¬(p ∨ q) ↔ ¬p ∧ ¬q := by
  apply Iff.intro
  · intro h ;apply And.intro;intro hp;exact h (Or.inl hp);intro hq;exact h (Or.inr hq)
  · intro h;intro hpq;apply Or.elim hpq;intro hp;exact False.elim (h.1 hp);intro hq;exact False.elim (h.2 hq)



variable (α : Type) ( p q : α → Prop)
variable (r : Prop)

-- Quantifier version of De Morgan's law:
-- ¬(∀ x, p x) ↔ ∃ x, ¬ p x
-- classical reasoning is used in the forward direction
example : (¬ ∀ x, p x) ↔ (∃ x, ¬ p x) := by
  apply Iff.intro
  · intro h
    · by_cases he : ∃ x, ¬ p x
      · exact he
      · have hpx : ∀ x, p x := by
          intros hx
          by_cases hp : p hx
          · exact hp
          · exact False.elim (he ⟨hx, hp ⟩)
        exact False.elim (h hpx)
  · intro h
    apply Exists.elim h
    intro x hx
    intro h_all
    have h_px := h_all x
    exact hx h_px

variable (p q r : Prop)

-- Contrapositive implies direct implication
-- classical proof of (¬q → ¬p) → (p → q)
example : (¬q → ¬p) → (p → q) := by
  intros h hp
  by_cases hq : q
  · exact hq
  · exact False.elim ((h hq) hp)

--NOT provable using intuitonist logic requires bycontradicto
example : (((p → q) → p) → p) := by
  sorry
